# What is a Random Number?

# Pseudo Random and True Random.

# Generate Random Number

In [1]:
# Generate a random integer from 0 to 100:

from numpy import random

x = random.randint(100)

print(x) 

25


# Generate Random Float

In [2]:
# Generate a random float from 0 to 1:

from numpy import random

x = random.rand()

print(x) 

0.7524891755631804


# Generate Random Array

# Integers

In [3]:
#Generate a 1-D array containing 5 random integers from 0 to 100:

from numpy import random

x=random.randint(100, size=(5))

print(x) 

[ 8 66 68 10 67]


In [4]:
#Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

from numpy import random

x = random.randint(100, size=(3, 5))

print(x) 

[[94 22 19 43 27]
 [ 5 49 74 92 47]
 [92 95 35 66 54]]


# Floats

In [5]:
# Generate a 1-D array containing 5 random floats:

from numpy import random

x = random.rand(5)

print(x) 

[0.79166116 0.95886386 0.5032269  0.98434939 0.94176374]


In [6]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers:

from numpy import random

x = random.rand(3, 5)

print(x) 

[[0.31162161 0.23838086 0.58994592 0.48878364 0.02301339]
 [0.61092688 0.95546475 0.29367132 0.23111439 0.68942371]
 [0.88196486 0.28530967 0.80967313 0.74649741 0.35777742]]


# Generate Random Number From Array

In [7]:
# Return one of the values in an array:

from numpy import random

x = random.choice([3, 5, 7, 9])

print(x) 

5


In [8]:
# Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x) 

[[9 7 9 9 7]
 [9 3 5 3 9]
 [7 7 3 7 9]]
